### ISSUE TITLE
用阿里邮箱发送失败

### ISSUE THREAD

**Issue by bbhxwl** [dotnet-campus/dotnetCampus.FileDownloader#43]
Run SendEmail -t *** -s "SendFile" -b "File" --Files file.zip --SmtpServer smtp.aliyun.com --SmtpServerPort 465 --UserName *** -***
通过 smtp.aliyun.com:465 发送 SendFile 到 ***
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at dotnetCampus.SendEmailTask.Program.Main(String[] args) in D:\a\dotnetcampus.DotNETBuildSDK\dotnetcampus.DotNETBuildSDK\SendEmailTask\Program.cs:line 86
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at dotnetCampus.DotNETBuild.CommandLineDragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath)
   at AutoGeneratedProgram.Main(String[] args) in D:\a\dotnetcampus.DotNETBuildSDK\dotnetcampus.DotNETBuildSDK\SendEmailTask\obj\Release\netcoreapp3.1\SendEmailTask.Program.g.cs:line 9
   at AutoGeneratedProgram.<Main>(String[] args)
/home/runner/work/_temp/2fc6e7cf-ca7c-49e4-a05c-d0895ba9e2e5.sh: line 1:  2825 Aborted                 (core dumped) SendEmail -t *** -s "SendFile" -b "File" --Files file.zip --SmtpServer smtp.aliyun.com --SmtpServerPort 465 --UserName *** -***
Error: Process completed with exit code 134.

**Comment by lindexi** [comment]
你是不是发错仓库了？
